### ISSUE TITLE
Turbine--Compute Normalized Flow Error

### ISSUE THREAD

**Issue by ck1313** [nasa/T-MATS#76]
In Turbine_TMATS.c, Compute Normalized Flow Error
line 345--346:
else if (IDes < 0.5)
        NErrorOut = (Nmech - NDes)/NDes;

Why use NDes as a error?
Why don't use PRmapDes as a error?  NErrorOut = (PRIn - PRmapDes)/PRmapDes;

**Comment by GRC-RHC-Sim** [comment]
ck1313, 

Thanks for commenting.  This error is calculated only when iDesign is turned on ( IDes = 0).  The iDesign feature calculates map scalars automatically to match the map with the current operating point. A scalar is applied to PRmapDes to match PRIn. Scalars will be 1 only if the map exactly matches the design operating point.

In other words:
Where, PRIn = (PRmap -1)*s_PR +1.  When IDes ==0 (iDesign on), s_PR is chosen so that this equation is true for the current point (map and actual operation). If IDes is off ( 1 or 2),  s_PR is an input and the block uses the default convergence criteria (mass flow).

-Jeff

**Comment by ck1313** [comment]
OK. Thanks for your answer. I forget the s_PR should be calculated.
-CK
