### ISSUE TITLE
On the input range

### ISSUE THREAD

**Issue by chengdingding** [nasa/T-MATS#86]
Dear Dr.Jeff
            I have consulted you before, and I feel a lot of benefit. Now I'm in trouble again. I hope to ask you for advice.
           For research needs, I now set the input to Wf and Ath.If the Wf settings are relatively small, such a phenomenon will occur after running the system.
"Warning in WfAthfanwei/While Iterator
Plant/Plant model/HPT, Error calculating WcMap. Vector definitions may need to be expanded.
Warning in WfAthfanwei/While Iterator
Plant/Plant model/HPT, Error calculating EffMap. Vector definitions may need to be expanded.
Warning in WfAthfanwei/While Iterator
Plant/Plant model/Fan, Error calculating SPR. Vector definitions may need to be expanded"
            Is this a normal phenomenon, please? Can we set this input in this way? If the input is set like this, can the results be trusted? I would be grateful if you could give you a suggestion.

-chengdingding

**Comment by GRC-RHC-Sim** [comment]
Cheng, 

The first two WcMap and EffMap errors are because you are going off the turbine map.  The SPR error is because the stall pressure ratio can't be calculated, going off the map as well.  

This happens when you try to operate at points where the model is not defined.  You can expand the maps as you see fit. This should be done with the use of data or a known map.  If those doesn't exist then keep in mind any additional map information may not match actual operation.

If you must operate in this area I would suggest expanding the maps. Even if the map data isn't the most accurate it is much better than just not converging.

Cheers,
-Jeff

Btw, I am not a Dr. :)
